### ISSUE TITLE
ENV line issue on mysql 5.5, 5.6 and 5.7 Dockerfiles

### ISSUE THREAD

**Issue by sardak** [oracle/docker#10]
Hey fellas,

There's an issue running the Dockerfiles for mysql 5.5 through 5.7:

    ENV PACKAGE_URL=http://repo.mysql.com/yum/mysql-5.7-community/docker/x86_64/mysql-community-server-minimal-5.7.7-0.3.rc.el7.x86_64.rpm

Y'all need to remove the `=` sign.

**Comment by Djelibeybi** [comment]
I have reported this to the MySQL team.

For any further MySQL bugs and issues, please submit a bug report at bugs.mysql.com under the category “MySQL Package Repos and Docker”.

I have asked them to update the README in their Github repo (we're just hosting a submodule version of the upstream repo at https://github.com/mysql/mysql-docker) so that it's clearer too. Sorry for the confusion.

**Comment by Djelibeybi** [comment]
Reported upstream: http://bugs.mysql.com/bug.php?id=76633&thanks=4
