### ISSUE TITLE
use /dev/urandom for weblogic:12.1.3-dev image

### ISSUE THREAD

**Issue by talberto** [oracle/docker#24]
The dockerfile used for building the image oracle/weblogic:12.1.3-dev defines but doesn't use the env var CONFIG_JVM_ARGS. The result is that weblogic takes 10 mins to start (in my machine) if we use the image weblogic:12.1.3-dev as the base image.

I propose adding the definition of the env var to the .bashrc file using something like that in the Dockerfile:
```
echo "export CONFIG_JVM_ARGS=$CONFIG_JVM_ARGS" >> ~/.bashrc
```

**Comment by brunoborges** [comment]
Thanks @Djelibeybi for calling my attention to this one. I'll be reviewing by the end of this week. Likely to merge into the sample code since it looks to be a reasonable configuration. Will test though.

Thanks @talberto for your suggestion.

**Comment by ovanekem** [comment]
I actually had to also set the same configuration when starting the domain (after domain creation), otherwise the startup of the domain was taking way too long (+10 mins).
In order to do that I added the following in the Dockerfile for domain creation (in samples/12c-domain):

```
ENV JAVA_OPTIONS -Djava.security.egd=file:///dev/./urandom
```

Also at same place I have added remote debugging information like -Xdebug -Xnoagent...

**Comment by brunoborges** [comment]
I will add the JAVA_OPTIONS but I will leave the debugging paramaters out since this is a sample and users should come up with their own. 

Thanks @ovanekem
